ref: experiment test fail

diff --git a/.github/workflows/flutter-test.yml b/.github/workflows/flutter-test.yml
--- a/.github/workflows/flutter-test.yml
+++ b/.github/workflows/flutter-test.yml
@@ -3,7 +3,7 @@
 # separate terms of service, privacy policy, and support
 # documentation.
 
-name: Dart
+name: Flutter test
 
 on:
   workflow_dispatch:
@@ -35,16 +35,19 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
 
-      # Uncomment this step to verify the use of 'dart format' on each commit.
-      # - name: Verify formatting
-      #   run: dart format --output=none --set-exit-if-changed .
+      - name: Run dart format
+        run: >
+          for f
+          in $(git diff origin/development..HEAD --relative --name-only -- lib/ test/ | grep '\.dart$') ;
+          do dart format --set-exit-if-changed $f ; done
 
-      # Consider passing '--fatal-infos' for slightly stricter analysis.
-      - name: Analyze project source
-        run: dart analyze
+      - name: Check Flutter for errors
+        run: flutter analyze --no-fatal-infos
 
-      # Your project will need to have tests in test/ and a dependency on
-      # package:test for this step to succeed. Note that Flutter projects will
-      # want to change this to 'flutter test'.
-      - name: Run tests
+      - name: Run Flutter tests
+        id: run_flutter_tests
         run: flutter test
+
+      - name: Fail check if tests failed
+        if: steps.run_flutter_tests.outcome != 'success'
+        run: echo 'Flutter tests failed, failing job'; exit 1
